### PR TITLE
Course categories, names and summaries are now processed through Moodle filters

### PR DESCRIPTION
**Pull request by michael-milette**
For more information, see #2 .

Best regards,

Michael Milette

### CODE REVIEW

**Comment by Flottertotte** [comment]
I really looks good and I would like to approve it, just one small question: why did you add ` $context = context_user::instance($USER->id);` 
(line 35)?

Thanks and Greetings
Flotter

**Comment by michael-milette** [comment]
Because I am using $context in line 45, 78, 79, 93 and 94 where it says:

    ['context' => $context]

Let me know if you have any other questions.

Best regards,

Michael

**Comment by Flottertotte** [comment]
Great, thanks and we will publish a new version on moodle asap.

**Comment by michael-milette** [comment]
Thank you Flotter! 🥇

**Pull request merged**
